go/porcelain/deploy.go

it was causing it to push to ..../deploys/xxx/abs/olute/path instead of ...xxx/path

use proper path, not the abs path

---

swagger.yml

There was a duplicated _review_id_ property in the _deploy_ definition.
This causes a problem with some tools that rely on successful parsing of the swagger file. For example [JS-YAML](http://nodeca.github.io/js-yaml/)

Remove duplicated `review_id` property.

---

go/models/site.go
swagger.yml
ui/swagger.json

This allows easy handover to a final netlify users at a later point

Allow setting a session_id when creating a new site

---

go/Gopkg.lock
go/porcelain/deploy.go

This allows to execute arbitrary logic during a deploy lifecycle.
Useful to generate progress reports and track file uploads in real time.

Add deploy callbacks.

---

go/porcelain/deploy.go

Add hooks to observe walking the deploy directories.

---

go/porcelain/deploy.go

This matches how the API handles these characters.

Check for invalid characters instead of escaping

---

go/models/site.go
swagger.yml
ui/swagger.json

This is attribute is an alias for the legacy site_plan that matches
other objects, like account.
Fixes #49

Add Site#capabilities

---

go/models/repo_info.go
swagger.yml
ui/swagger.json

POST and GET use the same attribute to access this information.
Fixes #64
/cc @mitchellh

Unify repository path accessors with RepoPath.

---

go/Gopkg.lock
go/Gopkg.toml
go/porcelain/http/http.go
go/porcelain/http/http_test.go
go/porcelain/netlify_client.go
swagger.yml
ui/swagger.json

Add a transport retry logic for rate limited requests. It's configured to try three times before backing off, or cancelling when the request is cancelled.
I've also added new factory functions to modify the number of attempts.
Fixes #58 

Implement an http transport that retries after a rate limit.

---

go/porcelain/http/http.go
go/porcelain/http/http_test.go

We keep having issues with closed streams in POST requests.

Disable H2 for retryable requests.

---

go/Gopkg.lock
go/Gopkg.toml
go/plumbing/operations/upload_deploy_function_parameters.go
go/porcelain/deploy.go
swagger.yml
ui/swagger.json

With AWSLambda supporting Go, I thought it'd be interesting to
do some exploration to support them.
Go support requires binary files, so we cannot depend on the file
extension to know if what we're uploading is JS or Go. Instead, we can
have a well known path convention to put Go binaries, like
`well-known-go`, and assume that all executables there are Go binaries.
We'd also need a way to tell our API that something should use the go
runtime and not the js runtime. I added a `Runtime` attribute to the file
bundle, so we can configure aws lambda with the right flags.

Upload go binaries as functions

---

go/porcelain/deploy.go
go/porcelain/netlify_client.go

We want to make this configurable for some customers to override.

add mone logging and some todos

---

go/porcelain/deploy.go
go/porcelain/deploy_unix.go
go/porcelain/deploy_windows.go

Fixes issues not deploying files under the right paths using Windows.
Fixes #86

Replace backslashes in file path names.

---

swagger.yml

Add User definition

---

go/porcelain/deploy.go

There was a bug around `getAssetManagementSha`. Because I reused the file `o`, the reader was already read with `io.Copy` and there was nothing to read at the point when try to see if it's LFS pointer file or not.
With this PR, we open a file again and read it. Also added some logging. Confirmed that it worked nicely with the flow with buildbot.

Fix the read file issue for asset management

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

open-api will talk to api when to make a new deploy, which is the list of files and shas:
```
{ "index.html": "file_sha", "foo.jpg": "pointer_file_sha:original_file_sha", "bar.html": "file_sha2"}
```
then, api response the following as required (need to upload these shas to api):
```
["file_sha", "pointer_file_sha"]
```
so that open-api knows that it needs to upload files that have these shas (index.html and foo.jpg).
Previously, open-api wasn't able to upload "foo.jpg" because it didn't recognize "pointer_file_sha" is about "foo.jpg". This PR fixes it.

Save sha without original sha when to save in Hashed

---

README.md

This adds a link to our js client code.

Add a mention of our js client to the open-api spec

---

go/models/deploy_site_capabilities.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
swagger.yml

Simple rename of the site capability from asset management to large media.

Rename asset management to large media (and LFS)

---

swagger.yml

I'm currently building a netlify menubar client and use [the netlify JS SDK](https://github.com/netlify/js-client). I found out that the swagger api definitions are missing the endpoint definition for a POST to `sites/$sitesId/builds` which is used by the netlify Admin UI to manually trigger builds (which is functionality I'd like to provide in the Netlify menubar app).
I talked to Dennis from support and he told me that the Netlify Admin UI is the source of truth. This PR adds documentation for the endpoint so that it'll be reflected in the JS Sdk and potentially Go SDK. :)

Add createSiteBuild endpoint

---

go/models/site.go
swagger.yml

This missing property is a hostname guaranteed to never changes.

Add Site's ID domain to the swagger definition.

---

CONTRIBUTING.md
go/models/deploy_site_capabilities.go
go/porcelain/deploy.go
swagger.yml

This flag needs to be renamed since it's conflicting with the usage capability and causing the build failure. Need to be shipped and used in buildbot to fix this.

Change large_media to large_media_enabled

---

swagger.yml

Documented use in https://github.com/netlify/cli-utils/issues/2#issuecomment-460399753
This adds parameters used by the API to set up default hooks and GitHub Apps integrations.

Add API driven configuration parameters

---

go/porcelain/deploy.go

Allow to pass options when there is no previous deploy.

Ignore nil deploys.

---

go/porcelain/deploy.go

I think that this will let us decouple during the async jobs.

add a wait until the deploy is ready

---

go/porcelain/netlify_client.go

We are also setting this as a default on BitBalloon, but in case anyone uses this elsewhere, they will get the correct default.

Change embedded DefaultSyncFileLimit to 500

---

go/porcelain/deploy.go

We decided we no longer need to poll here.  The reason we were polling was to fail the build prior to cache creation.  
This change, essentially allows for cache creation even if tree operations fail later, which is our fault most likely.

go-client: Don’t poll deploy after upload

---

go/porcelain/site.go

Hi, we updated an exported function comment based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

swagger.yml

Was marked as `string`, but api returns `integer`
Closes #162

Fix `installation_id` type

---

package.json

The `files` field in `package.json` includes files that are not meant to be imported and can be safely replaced by an empty array. This makes the npm package size smaller (`18KB` -> `12KB`)
The only file that is used by importers is the `swagger.json` which is the `main` field of `package.json`. The `main` field is always included by `npm publish`, i.e. does not need to be specified in `files`. 
The other two `js/*.js` files are not meant to be imported since those are build and release tasks. The YAML file is also not meant to be imported, the JSON file should be used instead.

Make npm package size smaller

---

swagger.yml

This adds [terms of services](https://swagger.io/specification/#infoObject) for the API.
I used this URL: https://www.netlify.com/legal/terms-of-use/
I am not sure if our API has a separate terms of use page.

Add terms of service

---

swagger.yml

This adds OpenAPI tags. This:
- groups endpoints according to categories/models. Having 100 endpoints at once is a little overwhelming otherwise.
- sort those groups by alphabetical order.

Add OpenAPI tags

---

swagger.yml

The `required` property [defaults to `false`](https://swagger.io/specification/v2/#fixed-fields-7), so it can be omitted when it is `false` to keep the specification simpler.

Remove `required: false`

---

swagger.yml

The current `splitTests` definition is parsed as:
```js
{ 
type: 'array', 
items: null, 
'$ref': '#/definitions/splitTest' 
}
```
Instead of:
```js
{ 
type: 'array', 
items: {
'$ref': '#/definitions/splitTest' 
} 
}
```

Fix YAML syntax error

---

.eslintrc.json

**- Summary**
This ensures the `require()` statements are grouped: first the core modules, then the node modules, then the local imports. This is much easier to browse code when imports/require are on top of the file and grouped.
The `import/order` ESLint rule is added so that the grouping happens automatically on `eslint --fix`, i.e. we don't need to think about it. This happens on save if your IDE supports (VSCode does). 
This also remove a disabled rule which did not need to be disabled.
**- Description for the changelog**
Group `require()` statements together.

Group `require()` statements

---

generate.go

Without this option some files were structured differently when regenerating. So adding this for consistency.

Fix options of go generation command

---

package.json

Fixes #219.
This repository's npm package main file is a JSON file.
Therefore this can be used with any Node.js version and the `engines.node` field is unnecessary.

Remove `engines.node`

---

go/plumbing/operations/cancel_site_deploy_parameters.go
go/plumbing/operations/cancel_site_deploy_responses.go
go/plumbing/operations/operations_client.go
swagger.yml

Fixing the path for canceling a deploy. Thanks for catching this @kitop !

Fix path for deploy cancel

---

go/porcelain/site.go

In reference to https://github.com/netlify/open-api/issues/98

add delete site to porcelain client

---

go/porcelain/deploy.go

I recently discovered that we do not deploy go functions with invalid permissions set.
This made me want to introduce a warning for it.
`DeployWarner` is an interface that consumers of this library can choose to implement on top of `DeployObserver`. Therefore this is not breaking.
I did not choose to implement a test because this is only a log output.

Warn if function conditions are not met

---

go/models/repo_info.go
swagger.yml

Add stop_builds property to repo info.
This is a property to configure the stopping builds for the site, see the following doc for more detail:
https://docs.netlify.com/configure-builds/stop-or-activate-builds/

Add stop_builds property to repo info

---

go/porcelain/deploy_test.go
go/porcelain/http/http.go

There's a race in our `RetryableTransport` because the submit method writes to an `http.Client` referenced by a pointer.
`uploadFile` is called concurrently here, which causes concurrent calls to `RetryableTransport.Submit`.
https://github.com/netlify/open-api/blob/29814e0eeb7075208b4bccdc16dea7da58fbc14c/go/porcelain/deploy.go#L372
I'm a bit uncertain about how the OpenApi runtime works. The `RetryableTransport` has an `http.RoundTripper` on it, but the `Submit` method also also takes an `op` with it's own `Client`. I'm not really sure which one is used when. Open to another solution if someone knows this package well.
This PR resolves the race by copying `op.Client` rather than setting a new `Transport` on it directly.
It also adds a test to call this method concurrently so that it can …

Fix race in RetryableTransport

---

swagger.yml

This PR adds documentation for the new beta endpoint to unlink a repo from a site.

Document `/sites/{site_id}/unlink_repo`

---

swagger.yml

It was deprecated and removed.

Remove support_priority field

---

swagger.yml

While having a chat in https://github.com/netlify/cli/issues/310#issuecomment-693473685, we realized that the swagger file definition of service instance is incorrect, especially with show/update/delete. These endpoints need to pass `instance_id`.

Fix service instance swagger definition

---

go/porcelain/deploy.go

Unfortunately, this is really waiting until the deploy is in the `ready` state, but we already have a public method called `WaitUntilDeployReady` that waits until the deploy is `ready` *or* `prepared` (ie ready to start uploading files).
I went with `WaitUntilDeployLive` because it mirrors the "Site is live" message that appears in the deploy logs. Open to other suggestions.
Closes #261 
Part of https://github.com/netlify/pod-the-builder/issues/47

Add WaitUntilDeployLive Go client method

---

go/plumbing/operations/show_service_responses.go
swagger.yml

It's a small bug, noticed while reviewing https://github.com/netlify/cli/pull/1344
Looks like this one is not currently used for any Netlify owned client (js-client, go client, CLI, etc.).
It's always nice to fix the bug whenever we notice!

Use service as a returned object for showService

---

swagger.yml

This will no longer be supported and will be retired in 30 days.

Mark listForms endpoint as deprecated

---

.github/workflows/test.yml

Should fix this build failure https://github.com/netlify/open-api/pull/269/checks?check_run_id=1487094976 since the previous version was using The `set-env` command which was deprecated.

Bump setup-go github action

---

go/plumbing/operations/operations_client.go
go/porcelain/forms.go
go/porcelain/forms_test.go
swagger.yml

This PR removes the deperecated listForms API endpoint from swagger.yml and regenerates the Go client.
https://github.com/netlify/bitballoon/issues/7814

Remove listForms endpoint

---

swagger.yml

We only accept title and branch as params, the rest are only part of the
response.

Fix createSiteBuildHook and updateSiteBuildHook params

---

README.md

This was removed when changing to the new layout.
See https://github.com/netlify/open-api/commit/0c6eacfede2b20d0cdc84ec71a2a6fdd81c1c534
Removing screenshot in README instead of updating, as it's easier to
keep up to date.
Close https://github.com/netlify/open-api/issues/254

Remove broken screenshot

---

.github/workflows/release-please.yml
.github/workflows/swagger-bump.yml
CONTRIBUTING.md
package-lock.json
package.json

This PR partially addresses #285. The idea is to provide a way to tag, release and bump the versions of both `package.json` and `swagger.yml` files. I tried running some tests on this repo but unfortunately seems like `release-please` will always create PRs against the mainline. As such I've ran some tests yesterday on a small repo - https://github.com/JGAntunes/actions-playground/pull/1 - testing `auto-commit`. The idea here is to rely on it as a workaround to bump the `swagger.yml` file based on `package.json` version (which is initially done by `release-please`).
For this to work I'll need to add a secret to the repo (currently don't have access, maybe you can help me witht it @erezrokah?), similar to what we've done, maybe we can use`netlify-bot`s access token? - …

chore: add release-please

---

.github/workflows/swagger-bump.yml
package.json

Currently the [release fails](https://github.com/netlify/open-api/runs/1741730586?check_suite_focus=true) because as part of `npm install/ci` we [run our tests](https://github.com/netlify/open-api/compare/fix/npm-scripts?expand=1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L53) which validate that the versions of the `package.json`  and `swagger.yml` match. I've just realised the `swagger-bump.js` has no external dependencies whatsoever, so running `npm install` isn't required. The alternative would be to drop that specific test from the `prepare` script which I'm not really comfortable with, given it forces us to run the tests before running `npm publish` which we still need to do locally.
It also removes the `prepublishOnly` script as well as the `version:*` …

fix(package.json): remove scripts no longer required and don't npm ci on swagger bump

---

package.json

CHANGELOG generation is now handled by `release-please` 👍

chore(prettier): disable CHANGELOG linting

---

.github/workflows/verify-go-src.yml
.gitignore

This picks up on what has been discussed on #285 and adds a step to verify that the go client is up to date and the files have been checked in (once again based on work @erezrokah did in the CLI 🙏 ). I've tested it in this PR by making some changes to  `swagger.yml` file and not generating a new client - https://github.com/netlify/open-api/runs/1742899676?check_suite_focus=true. - seems solid 😄
I've also added two files to the `.gitignore`, which I believe are only used as [helpers when generating the go glient](https://github.com/netlify/open-api/blob/master/generate.go#L4) and don't need to be checked in. Do tell me if that is not the case though.

chore(actions): check uncomitted go source code changes

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

Fixes https://github.com/netlify/buildbot/issues/1131
Previously, we were moving directories like `node_modules` to the cache after the build was finished but before deploying, so they weren't present at deploy time.
With build plugin steps that run after the site is live, we need to keep these directories around longer. This ignores them from the build directory root during deploy to maintain existing behavior.

Ignore cache directories in root of build directory when deploying

---

go/porcelain/context/context.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go

Part of https://github.com/netlify/buildbot/issues/1129
Rather than using the build's preprocess timelimit while waiting for a site to go live, we'd like to apply no timelimit other than the overall build timelimit.
Functions that wait for a deploy to enter a certain state take a context, so they don't need to also take a `timelimit` - the time limit can instead be added to the context, and the context's deadline/cancellation can be respected.
The gives users of this package more flexibility, because they can set a time limit on the context, or reuse a context that already has a timeout or cancellation function.
I also pushed setting the default preprocess time limit on `WaitUntilDeployReady` into the caller, `DoDeploy`. I think this is a better fit for the responsibilities of that …

feat!: support flexible cancelation while awaiting deploy state

---

go/plumbing/example_test.go

This code was in master but not the PR branch, so it didn't get the `v2` update all the other files got.

fix: use module v2 in package example

---

go/porcelain/deploy.go

I thought it would be nice to have the context of the `err` here. However, this `sharedErr` is getting updated by every file attempting to do the upload.
Here's what's happening:
* File 1 fails to upload after some retries with exponential backoff, and sets `sharedErr` saying it failed
* File 2 sees that `sharedErr` isn't nil, so it gives up as well, and wraps the `sharedErr` with its own message
* File 3 sees the *wrapped* `sharedErr` and wraps it again with its own message
* Repeat for files 4 - 100 to create a very ugly error
The causes a deeply nested error and it really doesn't look good. We're logging the original failure like below, so we can see it that way in the logs instead. https://github.com/netlify/open-api/blob/71cc689d4a5e3797563917d9c0e15a9270ecfec0/go/porcelain/deploy.go# …

fix: don't wrap sharedErr on failed upload

---

go.mod
go.sum
go/porcelain/deploy.go
go/porcelain/deploy_test.go

This was receiving from the semaphore twice (`sem <- 1`). Added a test and it's looking much better.

fix: don't double-count file uploads in worker pool

---

go/models/repo_info.go
swagger.yml

Allow specifying the functions directory when creating sites.

feat: add functions_dir in repo info

---

go/models/deploy.go
go/models/deploy_files.go
go/porcelain/deploy.go
swagger.yml

Allows setting the detected framework on a deploy and accessing the value from the API.
Part of https://github.com/netlify/pod-workflow/issues/159

feat: add framework to deploy properties

---

go/plumbing/operations/operations_client.go
go/plumbing/operations/rollback_site_deploy_responses.go
swagger.yml

Thanks to the report in https://answers.netlify.com/t/rollback-api-endpoint-returns-404/39157, we noticed the 🐛 in our swagger file. This endpoint was created as PUT (never was POST), so let's fix it.
reference: bitballoon route file https://github.com/netlify/bitballoon/blob/121b33b52afbb5a2842e5c8c78728d92ca0772bc/config/routes.rb#L238

fix: fix the HTTP method for the site rollback endpoint

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

- Adds a `FunctionSchedules` property to the deploy options when function schedules are detected
- Adds a `scheduled_functions` log field to an existing log message, showing the number of scheduled functions detected for the deploy
- Adds a new log message when a functions manifest file is detected

feat: add support for scheduled functions to Go client

---

go/plumbing/operations/upload_deploy_function_parameters.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
swagger.yml

When clients retry an operation, we would like to propagate the retry number to the API, so that it can adjust its behaviour accordingly.
To do this, this PR adds a `X-Nf-Retry-Count` header, which is empty on the first attempt, and contains `1` on the first retry, and so on.
Currently, we're adding the field to the `uploadDeployFunction` only.
Part of https://github.com/netlify/pod-compute/issues/140.

feat: add retry count field

---

package-lock.json
package.json
src/docs/build.js

This PR updates the [redoc-cli](https://www.npmjs.com/package/redoc-cli) dependency to upgrade the look and feel of our API reference docs. It also sorts the operation in the sidebar alphabetically, closing #388. 
1. Navigate to the [Deploy Preview](https://deploy-preview-390--open-api.netlify.app/) and ensure nothing seems buggy or out of place
2. Ensure that clicking on an operation in the sidebar adds a hash to the URL, and refreshing the page takes you to the same anchor

docs: update dependency redoc-cli

---

go/models/build_setup.go
swagger.yml

Fixes #398 and #396. Adds the missing `clear_cache` field to the `createSiteBuild` method.

fix(createSiteBuild): add clear_cache field

---

go/plumbing/operations/operations_client.go
swagger.yml

In the CLI and API docs, remove instances of `[Beta]` from netlify env commands and API reference.
Fixes https://github.com/netlify/pillar-workflow/issues/919 (1/2)

chore: remove beta tags from CLI and docs

---

.github/workflows/test.yml
.github/workflows/verify-go-src.yml

It will be easier debugging issues on checks failing on PRs by running
triggering them on the default branch, to rule out if the problem is
only in the PR or also on the default branch.
With this change, we should on the Actions tab above get a button to trigger manually like this:
Documentation:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
Part of #395

Allow triggering Test & Validate Go Client workflows manually

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go

Some work to support https://github.com/netlify/pod-compute/issues/192 in buildbot :)

feat: add functions_config parameter to deploy

---

go/models/function_config.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go
swagger.yml

Connected to: https://github.com/netlify/pod-compute/issues/350
Ensures we pass the generator field along with the functionsconfig when deploying serverless functions

feat: pass along generator to functionconfig

---

go/porcelain/deploy.go
go/porcelain/functions_manifest.go

Reads the runtimeVersion field from the function manifest and forwards it to the API endpoint
This is based on this PR were the new field was added:  https://github.com/netlify/zip-it-and-ship-it/pull/1367
https://github.com/netlify/pod-compute/issues/64

feat: add runtimeName support to deploy

---

README.md

Update link to JS Client as old repo is now archived and it has moved to the build mono repo.

chore: Update link to JS Client

---

go/models/site.go
swagger.yml

Update documentation for the new Site fields `branch_deploy_custom_domain` and 
`deploy_preview_custom_domain` supporting the Automatic deploy subdomains 
(https://answers.netlify.com/t/new-automatic-deploy-subdomains/87711/6)
Deploy preview:
https://deploy-preview-453--open-api.netlify.app/#tag/site/operation/createSite
(use the browser search for `branch_deploy_custom_domain` or 
`deploy_preview_custom_domain`)

fix: Update documentation for Automatic deploy subdomains

---

go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go

Follow-up to https://github.com/netlify/open-api/pull/454: the right property name from the functions manifest is `invocationMode` 🐫 , not `invocation_mode` 🐍.

fix: load `invocationMode` from manifest

---

.github/CODEOWNERS

Updating the CODOWNERS file to accomodate the reorg.
Changes are being made to replace no-longer-valid team names with the names of teams
that are replacing them, and adding what will be the new names for teams that should
exist post-reorg.
The code making these changes is in https://github.com/netlify/codeowners-scanner/
The announcement about this is in [#crew-engineering](https://netlify.slack.com/archives/CPJQSPQE4/p1683313309631019)
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift).</sub>

chore: update CODEOWNERS (bulk-codeowners)

---

go/models/env_var_value.go
go/models/set_env_var_value_params_body.go
swagger.yml

This issueless PR aims to address some feedback raised to the docs team by the support team.
The API docs are missing information on the env var property `context_parameter` which is used to specify a specific branch name for setting values per deploy context

fix: Add missing env var property - `context_parameter`

---

go/porcelain/deploy.go

remove extra unnecessary iteration over files

chore: remove extra unnecessary iteration over deploy files

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

While debugging [an issue with some files failing to upload](https://github.com/netlify/buildbot/issues/2793) we encountered that when calling: `defer wg.Wait()`
having a `return` statement, the return value would be assigned first, and then we would wait for the wait group, you can explore this issue on this playground link: https://go.dev/play/p/nuOytLQbkQy
Why it did not affect every single deploy?
Some Deploys returned some errors because they were blocked here: https://github.com/netlify/open-api/blob/master/go/porcelain/deploy.go#L433-L435 due to having too many files and waiting for the initialized semaphore, giving it a chance for `sharedErr` to have a value assigned before it be assigned to the `return` statement.

fix: race condition when waiting for sharedError

---

go/porcelain/deploy.go

Related with - https://github.com/netlify/pillar-workflow/issues/1126 - adding a field to our debug log line with the size of the file we're uploading.

chore(file-upload): log file size when uploading a file

---

go/models/function_route.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go
swagger.yml

Part of https://github.com/netlify/pod-dev-foundations/issues/579, based on https://github.com/netlify/open-api/pull/481.

feat: support function route `methods` field

---

go/porcelain/deploy.go

Trying to debug the issues face by the dev-foundations team on this PR: https://github.com/netlify/open-api/pull/478#discussion_r1316212994
I noticed that the interface in`apierrors.Error` has different function signatures than the types returned by `UploadDeployFile` and `UploadDeployFunction`
since we do safe casting `.()` this failed silently and went unnoticed.
In this changes I implement an interface that matches the signature of the errors returned by those two functions and defined the function we need to use (`Code() int`)

 fix: fileUpload error casting does not conform to interface 

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go
swagger.yml

Related with - https://github.com/netlify/buildbot/issues/2886
Adds a porcelain utility method to poll for state `processed`.

feat(go-client): add poll for processed

---

go/models/create_env_vars_params_body_items.go
go/models/env_var.go
go/models/function_config.go
go/models/update_env_var_params_body.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go
swagger.yml

Adds build data to surface information about the serverless functions api and netlify/build
Part of https://linear.app/netlify/issue/COM-6/expose-the-ability-to-query-for-functions-using-the-v2-api

feat: Add build data for observability

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

In https://github.com/netlify/open-api/pull/490, we made the switch to upload ZISI-compiled Go functions as `provided.al2`. This has been rolled out successfully, so now we can also make this switch for files that weren't compiled by ZISI.
Part of https://github.com/netlify/pod-dev-foundations/issues/581.

fix: upload non-zisi-compiled files as `provided.al2`

---

go/models/deploy_files.go
go/porcelain/deploy.go
swagger.yml

Issue: https://linear.app/netlify/issue/COM-75/add-framework-version-parameter-to-open-api-deployfiles
The new field it's added to the deploy files. The framework is added [here](https://github.com/netlify/open-api/blob/b041a0fd6b17bd8d21529240110f146a430bd789/go/porcelain/deploy.go#L268) as well, but I think that's just for deploy creation? And we will be updating the deploy

feat: Added framework_version

---

package-lock.json
package.json

Replicates the results of clicking the "Download" button in the UI, so that the OpenAPI v3 spec can be accessed directly

chore(docs): output OpenAPI v3 spec

---

package-lock.json
package.json
src/convert.js

refactor: replace make-dir with fs/mkdir
- replace functionality related to create a directory
- remove dependency make-dir no longer needed
Related to https://github.com/netlify/cli/issues/3941

refactor: replace promisify with fs/promises version on convert.js

---

go/models/function_config.go
go/plumbing/operations/upload_deploy_function_parameters.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
go/porcelain/functions_manifest.go
swagger.yml

Part of https://linear.app/netlify/issue/COM-770/transfer-timeout-property-from-zisi-to-netlify-server.

feat: support function timeout property

---

go/porcelain/functions_manifest.go

The functions manifest uses camelCase! 🤦🏻

fix: use correct casing in excluded routes property

---

.github/workflows/release-please.yml
go/plumbing/operations/operations_client.go
package-lock.json
package.json
redocly.yml
swagger.yml

Generate typescript types from the swagger.yaml and ship them as part of the npm package
Had to use a very old version of the openapi typescript package 5.x or below to conform with the swagger 2.0 version

feat: add typescript types to package

---

go/models/site.go
swagger.yml

Part of FRP-1269 - https://linear.app/netlify/issue/FRP-1269/information-request-is-the-account-id-available-for-build-plugins - as I was looking through the properties we return on the get site endpoint I noticed we're not listing the `account_id` (and we are returning it already) this just clarifies that and updates our open API spec.

fix(getSite): add account_id to the list of returned props

---

go/plumbing/operations/get_current_user_responses.go
swagger.yml

`getCurrentUser` response schema was incorrectly set as an array but should just be a single user object.

fix: update `getCurrentUser` response type from array to single `User` object

---

go/plumbing/operations/get_account_responses.go
swagger.yml

This PR fixes the incorrect response type for the `getAccount` endpoint in the OpenAPI specification.
The `getAccount` endpoint was incorrectly documented as returning an array of `accountMembership` objects:
```yaml
schema:
type: array
items:
$ref: '#/definitions/accountMembership'
```
However, the actual API returns a single `accountMembership` object, not an array.
Updated the response schema to correctly reflect a single object:
```yaml
schema:
$ref: '#/definitions/accountMembership'
```
This change brings the `getAccount` endpoint in line with other similar single-object endpoints like:
- `createAccount`
- `updateAccount` 
- `getCurrentUser`
- ✅ All existing tests pass
- ✅ Build process completes successfully
- ✅ Generated TypeScript types are correct
- ✅ Documentation builds without …

fix: update `getAccount` response type from array to single account object
