netlify/open-api

go/plumbing/operations/operations_client.go
go/porcelain/deploy.go
go/porcelain/netlify_client.go
swagger.yml

Deploy a site from a given directory.

Add porcelain deploy.

---

go/porcelain/deploy.go

Do not try to upload 0 files.

---

go/porcelain/site.go

So we can show up to date settings.

Make site update to return the updated site.

---

go/porcelain/auth.go

Add a function to wait until an auth ticket is authorized by the server.

---

go/porcelain/deploy.go

This is a quick fix to make sure we don't load all files into memory but stream them from disk instead while uploading.

Make sure we don't load all files in memory during a deploy

---

go/porcelain/site.go

Take a site setup as an argument.

Fix calls to Create and Update sites.

---

go/plumbing/operations/delete_site_responses.go
go/plumbing/operations/operations_client.go
swagger.yml
ui/swagger.json

Fix response status code for delete site operation

---

go/plumbing/operations/create_site_build_hook_responses.go
swagger.yml
ui/swagger.json

Fix reference to return type creating build hook.

---

go/porcelain/netlify_client.go

- So we keep backwards compatibility.

Allow non-rate limited retryable clients.

---

go/porcelain/deploy.go

Do not keep all file handles open at the same time

---

go/plumbing/operations/list_forms_parameters.go
go/porcelain/forms.go
swagger.yml
ui/swagger.json

I added functions in the porcelain package to be able to list forms as well as list form submissions. This is a prerequisite to add functionality to list these inside netlifyctl.

Add forms functions to porcelain

---

appveyor.yml
go/porcelain/deploy_unix.go
go/porcelain/deploy_windows.go
go/porcelain/deploy_windows_test.go

Fix run conversion on Windows.

---

go/porcelain/deploy.go

This allows node based functions bundled as a zip file instead of a single .js file. This will allow us to support compiled node extensions.

Allow deploying zip files as js functions

---

README.md

I just went through a new release step. Let's document it.

Update README for making a new release

---

ui/index.js

Closes https://github.com/netlify/open-api/issues/117

Fix anchor links

---

Makefile
README.md
go/plumbing/operations/upload_deploy_file_parameters.go
go/plumbing/operations/upload_deploy_function_parameters.go
go/porcelain/deploy.go
go/porcelain/deploy_test.go
swagger.yml

So we can store that information.

Read original size from lfs pointers.

---

swagger.yml

Formatted using the YAML vscode plugin

---

swagger.yml

Depends on https://github.com/netlify/bitballoon/pull/3467 getting merged and deployed.

Add build_image property to site definition

---

.travis.yml

Use go proxy

---

package.json

This is a tiny PR that re-order npm scripts so they follow their logical order.

Re-order npm scripts

---

package-lock.json
package.json

Fixes #213.
This upgrades Redoc in order to fix a scrolling issue on Chrome `80`.

Fix menu scrolling on Chrome

---

swagger.yml

Blocked on: https://github.com/netlify/bitballoon/pull/6224

Add 'branch' to createSiteDeploy

---

swagger.yml

fix sites typo on split test endpoint paths

---

go/models/site.go
swagger.yml

Add prerender property to site

---

.github/workflows/labeler.yml

Use @erezrokah awesome lebeler to tag PRs with the required `type: <type>` label based on the title.

chore(actions): add labeler

---

.github/workflows/test.yml
.github/workflows/verify-go-src.yml

As per suggested in #292 - https://github.com/netlify/open-api/pull/292#discussion_r562019180
CC @mraerino

chore(actions): use go v1.15.x

---

.github/workflows/release-please.yml
.github/workflows/test.yml
CONTRIBUTING.md
package.json

Adds `npm` publishing automation

chore: automate npm publishing

---

package.json

This fixes the `npm publish` automation

fix: npm automation

---

.github/workflows/release-please.yml
.github/workflows/swagger-bump.yml
.github/workflows/test.yml

Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.

chore: run CI on latest Node.js

---

go/plumbing/operations/operations_client.go
swagger.yml

This PR adds an additional note for all the Envelope endpoints to enable the feature in Netlify UI before hitting the endpoints.

chore(docs): add a note about enabling the beta experience in Netlify UI

---

go/models/create_env_vars_params_body_items.go
go/models/env_var.go
go/models/update_env_var_params_body.go
swagger.yml

This PR is the open-api portion of https://github.com/netlify/pillar-workflow/issues/808, and related to https://github.com/netlify/cli/pull/5143. Our API supports both snake_case and kebab-case, but for consistency with deploy context values like `deploy-preview` and `branch-deploy`, we are moving the developer-facing recommended keys to be kebab-case.

chore: kebab-case post-processing flag

---

go/models/deploy_files.go
go/plumbing/operations/operations_client.go
swagger.yml

Adding a new functions_config property to deployfiles for 
https://github.com/netlify/pod-compute/issues/156
and connected to https://github.com/netlify/bitballoon/pull/13556

feat: add functions_config property to deployfiles

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

Addresses the `open-api` part of this issue: https://github.com/netlify/netlify-server/issues/2626

fix: upload a single file per sha

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

Related to https://github.com/netlify/netlify-server/issues/2833
We need to be able to access these files at deploy time. Implementation done following the same pattern used for edge functions.
@4xposed @JGAntunes tagging you both as reviewers because I think it's more relevant to your team.

feat: support for edge-redirects manifests

---

go/porcelain/deploy.go
go/porcelain/deploy_test.go

Related to https://github.com/netlify/netlify-server/pull/2873

Update edge-redirects dir path

---

go/models/create_env_vars_params_body_items.go
go/models/env_var.go
go/models/update_env_var_params_body.go
go/plumbing/operations/operations_client.go
swagger.yml

This pull request adds a new `is_secret` boolean to the `createEnvVars` and `updateEnvVar` endpoints.

chore(docs): support `is_secret` boolean on environment variables

---

swagger.yml

fix: document functions_region for sites

---

go/models/function_config.go
go/porcelain/deploy.go
go/porcelain/functions_manifest.go
swagger.yml

feat: add `priority` field to functions config

---

go/models/account_add_member_setup.go
go/models/account_update_member_setup.go
swagger.yml

updating to reflect a the developer role rename, and adding reviewers, which can now be added using the general members endpoint

feat: rename collaborator to developer, add reviewer role

---

go/models/create_env_vars_params_body_items.go
go/models/env_var.go
go/models/update_env_var_params_body.go
swagger.yml

This is a public repo, so please see additional details in Linear.

feat: unmark secret environment variables as enterprise-only
